github.com:
    users:
        cviper13:
            oauth_token: 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
    git_protocol: https
    user: cviper13
    oauth_token: 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
