source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/programs.conf
source = $HOME/.config/hypr/colors.conf
source = $HOME/.config/hypr/autostart.conf
source = $HOME/.config/hypr/enviromentVariables.conf
source = $HOME/.config/hypr/appearance.d/*.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/keybindings.conf
source = $HOME/.config/hypr/windowRules.d/*.conf
source = $HOME/.config/hypr/events.d/*.conf
