input {
    kb_layout = tr
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = -0.7 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

gestures {
    workspace_swipe = true
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# Touchpad 1 Configuration
device {
    name = elan0412:00-04f3:3162-touchpad
    sensitivity = 0
}

# Touchpad 2 Configuration
device {
    name = "etps/2-elantech-touchpad"
    sensitivity = 1.0
}

# Mouse Configuration
device {
    name = "elan0412:00-04f3:3162-mouse"
    sensitivity = 1.0
}
