windowrulev2 = pin,class:deadlocked,title:^$
windowrulev2 = float,class:deadlocked,title:^$
windowrulev2 = noborder,class:deadlocked,title:^$
windowrulev2 = nodim,class:deadlocked,title:^$
windowrulev2 = noinitialfocus,class:deadlocked,title:^$
windowrulev2 = noblur,class:deadlocked
