#####################
### BORDER CONFIG ###
#####################

general {
    border_size = 2

    col.active_border = rgba(aaaaaaee) rgba(ffffffee) 45deg
    col.inactive_border = rgba(595959aa)

    resize_on_border = false
}
