#####################
### BORDER CONFIG ###
#####################

general {
    border_size = 2

    col.active_border = $color1 $color9 45deg
    col.inactive_border = $color7 $color15 45deg

    resize_on_border = false
}
